package kbapi

type EndpointExceptionsListItem struct {
	// CreatedAt Autogenerated date of object creation.
	CreatedAt string `json:"created_at,omitempty"`
	// CreatedBy Autogenerated value - user that created object.
	CreatedBy string    `json:"created_by,omitempty"`
	Comments  []Comment `json:"comments,omitempty"`
	// Description Describes the exception list.
	Description string  `json:"description,omitempty"`
	Entries     []Entry `json:"entries,omitempty"`
	// ID Exception list's identifier.
	ID        string `json:"id,omitempty"`
	Immutable bool   `json:"immutable,omitempty"`
	// ListID Exception list's human readable string identifier, e.g. `trusted-linux-processes`.
	ListID string `json:"list_id,omitempty"`
	// Meta Placeholder for metadata about the list container.
	Meta *map[string]interface{} `json:"meta,omitempty"`
	// Name The name of the exception list.
	Name string `json:"name,omitempty"`
	// NamespaceType Determines whether the exception container is available in all Kibana spaces or just the space
	// in which it is created, where:
	//
	// - `single`: Only available in the Kibana space in which it is created.
	// - `agnostic`: Available in all Kibana spaces.
	NamespaceType string `json:"namespace_type,omitempty"`
	// OsTypes Use this field to specify the operating system. Only enter one value.
	// Values are linux, macos, or windows.
	OsTypes *[]string `json:"os_types,omitempty"`
	// Tags String array containing words and phrases to help categorize exception containers.
	Tags *[]string `json:"tags,omitempty"`
	// TieBreakerID Field used in search to ensure all containers are sorted and returned correctly.
	TieBreakerID string `json:"tie_breaker_id,omitempty"`
	// Type The type of exception list to be created. Different list types may denote where they can be utilized.
	// Values are detection, rule_default, endpoint, endpoint_trusted_apps, endpoint_events,
	// endpoint_host_isolation_exceptions, or endpoint_blocklists.
	Type string `json:"type,omitempty"`
	// UpdatedAt Autogenerated date of last object update.
	UpdatedAt string `json:"updated_at,omitempty"`
	// UpdatedBy Autogenerated value - user that last updated object.
	UpdatedBy string `json:"updated_by,omitempty"`
	// Version The document version, automatically increasd on updates.
	Version int `json:"version,omitempty"`
	// VersionUnderscored The version id, normally returned by the API when the item was retrieved.
	// Use it ensure updates are done against the latest version.
	VersionUnderscored *string `json:"_version,omitempty"`
}

type Comment struct {
	Comment   string `json:"comment"`
	CreatedAt string `json:"created_at"`
	CreatedBy string `json:"created_by"`
	ID        string `json:"id"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy string `json:"updated_by"`
}

type Entry struct {
	Field    string     `json:"field"`
	Operator string     `json:"operator"`
	List     *EntryList `json:"list,omitempty"`
	Type     string     `json:"type"`
	Value    string     `json:"value"`
}

type EntryList struct {
	ID string `json:"id"`
	// Specifies the Elasticsearch data type of excludes the list container holds. Some common examples:
	//
	// keyword: Many ECS fields are Elasticsearch keywords
	// ip: IP addresses
	// ip_range: Range of IP addresses (supports IPv4, IPv6, and CIDR notation)
	//
	// Values are binary, boolean, byte, date, date_nanos, date_range, double, double_range, float, float_range, geo_point, geo_shape,
	// half_float, integer, integer_range, ip, ip_range, keyword, long, long_range, shape, short, or text.
	Type string `json:"type"`
}
